// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AvroProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("AvroProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing AvroProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AvroProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "AvroProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing AvroProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
